name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  publish:
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: dotnet test
      
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: ssh-keyscan 209.97.129.212 >> ~/.ssh/known_hosts

      - run: ssh -tt david2@209.97.129.212 'rm -rf /var/www/manx-corpus/CorpusSearch/OpenData/{*,.*}'
        continue-on-error: true
        timeout-minutes: 4
      
      - name: Pull and Copy Open Data
        run: ssh -tt david2@209.97.129.212 'cd ~/manx-search-data && git pull origin master && cp -r ~/manx-search-data/OpenData /var/www/manx-corpus/CorpusSearch'
        
        # ignore the output of rm -rf and continue
      - name: Refresh Closed Data from GitHub Repo
        run: ssh -t david2@209.97.129.212 'rm -rf /var/www/manx-corpus/CorpusSearch/ClosedData/{*,.*} || cd ~/corpus-search-data-private && git pull origin master && cp -r ~/corpus-search-data-private/ClosedData /var/www/manx-corpus/CorpusSearch/'
                
      - name: Rebuild
        run: ssh -t david2@209.97.129.212 'sudo /bin/systemctl stop manx-corpus.service && cd /var/www/manx-corpus/ && dotnet publish --framework net6.0 --configuration Release'
            
        # even if the above fails, we want a working site
      - name: Restart Service
        run: ssh -t david2@209.97.129.212 'sudo /bin/systemctl start manx-corpus.service'
